### ISSUE TITLE
fix link

### ISSUE THREAD

**Issue by mldchan** [BreadTeleporter/BreadTeleporter#1]
https://github.com/BreadTeleporter/BreadTeleporter/blob/55fe50c28d1293174535052e28425ed3bc3bd3fb/README.md?plain=1#L5

fix old link

**Comment by mldkyt** [comment]
![image](https://github.com/BreadTeleporter/BreadTeleporter/assets/59791284/080b4f32-9ab6-4688-9e66-52de9987b84e)

it works but is insecure :3

**Comment by breadtf** [comment]
it **should** 301 redirect, will fix
